NAME_TO_PREFIX = {
    "Алёнка": "alena",
    "Алёна": "alena",
    "Водяная": "vodyanaya",
    "Данил": "danil",
    "Елисеев": "eliseyev",
    "Иванушка": "kozlenok",
    "Зося": "zosia",
    "Садко": "sadko",
    "Светлана": "svetlana",
    "Терентий": "terenty",
    "Алик": "alik",
    "Берёзка": "policewoman",
    "Дядя Боря": "boris",
    "Левша": "levsha",
    "Юрка": "urka",
    "Воронар": "voronar",
    "Илья": "ilya",
    "Чернава": "chernava",
    "Врач": "doctor",
    "Зайчище": "bunny",
    "???": "",
    "Мама": "olga",
    "Диво": "divo",
    "Услад": "uslad",
    "Прослав": "divo",
    "Робот?": "divo",
    "Баюшка": "bayushka",
    "Альфёдор": "butler",
    "Квакентий": "frog",
    "Князь": "king",
    "Навь": "navya",
    "Пёс-Сторож": "watchman",
    "Жар-Птица": "firebird",
    "Жыж": "jij",
    "Кощей": "koshchei",
    "Огнезмей": "firesnake",
}